//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "departments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub department_category: String,
    pub head_id: Option<i32>,
    pub status: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::employee_position::Entity")]
    EmployeePosition,
    #[sea_orm(
        belongs_to = "super::employees::Entity",
        from = "Column::HeadId",
        to = "super::employees::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Employees,
    #[sea_orm(has_many = "super::polyclinic::Entity")]
    Polyclinic,
    #[sea_orm(has_many = "super::position_titles::Entity")]
    PositionTitles,
}

impl Related<super::employee_position::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmployeePosition.def()
    }
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::polyclinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Polyclinic.def()
    }
}

impl Related<super::position_titles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionTitles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
