//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "doctors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub employee_id: i32,
    pub specialization: String,
    #[sea_orm(unique)]
    pub license_number: String,
    pub room_code: String,
    pub polyclinic_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::doctor_schedules::Entity")]
    DoctorSchedules,
    #[sea_orm(
        belongs_to = "super::employees::Entity",
        from = "Column::EmployeeId",
        to = "super::employees::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Employees,
    #[sea_orm(
        belongs_to = "super::polyclinic::Entity",
        from = "Column::PolyclinicId",
        to = "super::polyclinic::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Polyclinic,
    #[sea_orm(
        belongs_to = "super::rooms::Entity",
        from = "Column::RoomCode",
        to = "super::rooms::Column::Code",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Rooms,
}

impl Related<super::doctor_schedules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DoctorSchedules.def()
    }
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::polyclinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Polyclinic.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rooms.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
