//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "employees")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub full_name: String,
    #[sea_orm(unique)]
    pub nip: Option<String>,
    #[sea_orm(unique)]
    pub email: String,
    #[sea_orm(unique)]
    pub phone: String,
    pub birth_date: Date,
    pub hire_date: Date,
    pub address: String,
    pub employment_status: String,
    pub department_code: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentCode",
        to = "super::departments::Column::Code",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Departments,
    #[sea_orm(has_one = "super::doctors::Entity")]
    Doctors,
    #[sea_orm(has_many = "super::employee_position::Entity")]
    EmployeePosition,
    #[sea_orm(has_one = "super::nurses::Entity")]
    Nurses,
    #[sea_orm(has_one = "super::user::Entity")]
    User,
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::doctors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Doctors.def()
    }
}

impl Related<super::employee_position::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EmployeePosition.def()
    }
}

impl Related<super::nurses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nurses.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
