//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "employee_position")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub employee_id: i32,
    pub position_title_id: i32,
    pub department_code: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::departments::Entity",
        from = "Column::DepartmentCode",
        to = "super::departments::Column::Code",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Departments,
    #[sea_orm(
        belongs_to = "super::employees::Entity",
        from = "Column::EmployeeId",
        to = "super::employees::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Employees,
    #[sea_orm(
        belongs_to = "super::position_titles::Entity",
        from = "Column::PositionTitleId",
        to = "super::position_titles::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PositionTitles,
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Departments.def()
    }
}

impl Related<super::employees::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Employees.def()
    }
}

impl Related<super::position_titles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PositionTitles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
