//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod departments;
pub mod doctor_schedules;
pub mod doctors;
pub mod employee_position;
pub mod employees;
pub mod nurses;
pub mod nurses_polyclinic_assignments;
pub mod patients;
pub mod patients_visit_intent;
pub mod polyclinic;
pub mod position_titles;
pub mod queue_ticket;
pub mod referral_documents;
pub mod rooms;
pub mod user;
