//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nurses_polyclinic_assignments")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub nurse_id: i32,
    pub polyclinic_id: i32,
    pub assigned_since: DateTime,
    pub assigned_until: Option<DateTime>,
    pub notes: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::nurses::Entity",
        from = "Column::NurseId",
        to = "super::nurses::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Nurses,
    #[sea_orm(
        belongs_to = "super::polyclinic::Entity",
        from = "Column::PolyclinicId",
        to = "super::polyclinic::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Polyclinic,
}

impl Related<super::nurses::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Nurses.def()
    }
}

impl Related<super::polyclinic::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Polyclinic.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
