//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::departments::Entity as Departments;
pub use super::doctor_schedules::Entity as DoctorSchedules;
pub use super::doctors::Entity as Doctors;
pub use super::employee_position::Entity as EmployeePosition;
pub use super::employees::Entity as Employees;
pub use super::nurses::Entity as Nurses;
pub use super::nurses_polyclinic_assignments::Entity as NursesPolyclinicAssignments;
pub use super::patients::Entity as Patients;
pub use super::patients_visit_intent::Entity as PatientsVisitIntent;
pub use super::polyclinic::Entity as Polyclinic;
pub use super::position_titles::Entity as PositionTitles;
pub use super::queue_ticket::Entity as QueueTicket;
pub use super::referral_documents::Entity as ReferralDocuments;
pub use super::rooms::Entity as Rooms;
pub use super::user::Entity as User;
