//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub use super::patients::Entity as Patients;
pub use super::patients_visit_intent::Entity as PatientsVisitIntent;
pub use super::queue_ticket::Entity as QueueTicket;
