//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "account_status")]
pub enum AccountStatus {
    #[sea_orm(string_value = "PENDING_VERIFICATION")]
    PendingVerification,
    #[sea_orm(string_value = "AWAITING_SETUP")]
    AwaitingSetup,
    #[sea_orm(string_value = "ACTIVE")]
    Active,
    #[sea_orm(string_value = "SUSPENDED")]
    Suspended,
}
